//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jlsEntitiesFinanceiro : DbContext
    {
        public jlsEntitiesFinanceiro()
            : base("name=jlsEntitiesFinanceiro")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acesso> Acesso { get; set; }
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<EntradaProdutoRegistro> EntradaProdutoRegistro { get; set; }
        public virtual DbSet<Fornecedor> Fornecedor { get; set; }
        public virtual DbSet<Funcao> Funcao { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<OrcamentoRegistro> OrcamentoRegistro { get; set; }
        public virtual DbSet<PedidoRegistro> PedidoRegistro { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<TipoFornecedor> TipoFornecedor { get; set; }
        public virtual DbSet<TipoPagamento> TipoPagamento { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
        public virtual DbSet<VendaRegistro> VendaRegistro { get; set; }
        public virtual DbSet<EntradaProdutoDetalhe> EntradaProdutoDetalhe { get; set; }
        public virtual DbSet<OrcamentoDetalhe> OrcamentoDetalhe { get; set; }
        public virtual DbSet<VendaDetalhe> VendaDetalhe { get; set; }
    }
}
