//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoRegistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrcamentoRegistro()
        {
            this.OrcamentoDetalhe = new HashSet<OrcamentoDetalhe>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> FuncionarioId { get; set; }
        public System.DateTime DataOrcamento { get; set; }
        public decimal ValorTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoDetalhe> OrcamentoDetalhe { get; set; }
    }
}
