//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoRegistro
    {
        public int Id { get; set; }
        public System.DateTime DataPedido { get; set; }
        public decimal ValorPedido { get; set; }
        public int FornecedorId { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
