//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.EntradaProdutoDetalhe = new HashSet<EntradaProdutoDetalhe>();
            this.OrcamentoDetalhe = new HashSet<OrcamentoDetalhe>();
            this.VendaDetalhe = new HashSet<VendaDetalhe>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public decimal ValorCompra { get; set; }
        public decimal ValorVenda { get; set; }
        public int NumEstoque { get; set; }
        public int NumEstoqueCritico { get; set; }
        public bool Ativo { get; set; }
        public int UnidadeId { get; set; }
        public int FornecedorId { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaProdutoDetalhe> EntradaProdutoDetalhe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoDetalhe> OrcamentoDetalhe { get; set; }
        public virtual Unidade Unidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendaDetalhe> VendaDetalhe { get; set; }
    }
}
