//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaRegistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendaRegistro()
        {
            this.VendaDetalhe = new HashSet<VendaDetalhe>();
        }
    
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public int FuncionarioId { get; set; }
        public int TipoPagamentoId { get; set; }
        public System.DateTime DataVenda { get; set; }
        public decimal ValorSugerido { get; set; }
        public decimal Desconto { get; set; }
        public decimal TotalVenda { get; set; }
        public int Parcelas { get; set; }
        public System.DateTime PrimVencimento { get; set; }
        public bool Ativo { get; set; }
        public decimal Recebeu { get; set; }
        public decimal Juro { get; set; }
        public decimal Restante { get; set; }
        public decimal ValorFinal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendaDetalhe> VendaDetalhe { get; set; }
    }
}
